
[[redirects]]
  from = "/bigcommerce/*"
  to = "https://api.bigcommerce.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[headers]]
  for = "*"
  [headers.values]
    Access-Control-Allow-Origin = "*"